# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port if needed (FastMCP uses stdio by default)
# No port exposure necessary for stdio transport

# Default command to run the MCP server
CMD ["python", "app.py"]
